spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useSSL=false
    username: root
    password: admin
  rabbitmq:
    host: 192.168.99.100
    password: guest
    port: 5672
    username: guest
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: product:${server.port}
info:
  app.name: product
  company.name: www.weifuwukt.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
