server:
  port: 10001
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useSSL=false
    username: root
    password: admin
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

info:
  app.name: product
  company.name: www.weifuwukt.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
